### ISSUE TITLE
识别字幕提示找不到目录

### ISSUE THREAD

**Issue by 62019** [coder-pig/VideoSubtitleExtractTool#1]
![1633269410(1)](https://user-images.githubusercontent.com/45893860/135756894-fc3365e6-f003-4965-a27a-62c6c873fc67.jpg)

**Comment by 62019** [comment]
![image](https://user-images.githubusercontent.com/45893860/135756931-e688d31d-4575-4025-bf84-c6e7fef646ff.png)

**Comment by coder-pig** [comment]
ffmpeg环境没有安装，安装下就好了
